import { Color, FlowerType, Size, Style } from "@/app/generated/prisma/enums";

export const ProductsData = [
  {
    slug: "luxury-pink-peony-bouquet",
    images: [
      { url: "/images/Peony.png", alt: "دسته گل پپیونی صورتی لوکس" },
      { url: "/images/Peony.png", alt: "دسته گل پپیونی صورتی لوکس" },
      { url: "/images/Peony.png", alt: "دسته گل پپیونی صورتی لوکس" },
    ],

    title: "دسته گل پپیونی صورتی لوکس",
    rate: 4.5,
    price: 5000000,
    discount: 55,
    isBestSeller: true,
    stock: 6,
    flowerType: FlowerType.peony,
    style: Style.modern,
    size: Size.large,
    colors: [Color.pink],
    categories: ["congratulations-flowers"],
  },
  {
    slug: "classic-white-rose-bouquet",
    images: [
      { url: "/images/SympathyFlowers.png", alt: "دسته گل رز سفید کلاسیک" },
      { url: "/images/SympathyFlowers.png", alt: "دسته گل رز سفید کلاسیک" },
      { url: "/images/SympathyFlowers.png", alt: "دسته گل رز سفید کلاسیک" },
    ],
    title: "دسته گل رز سفید کلاسیک",
    rate: 4.5,
    price: 3499000,
    discount: 55,
    isBestSeller: false,
    stock: 10,
    flowerType: FlowerType.rose,
    style: Style.classic,
    size: Size.medium,
    colors: [Color.white],
    categories: ["rose-bouquet", "congratulations-flowers"],
  },
  {
    slug: "summer-sunflower-bouquet",
    images: [
      { url: "/images/sunflowers.png", alt: "دسته گل آفتابگردان تابستانی" },
      { url: "/images/sunflowers.png", alt: "دسته گل آفتابگردان تابستانی" },
    ],

    title: "دسته گل آفتابگردان تابستانی",
    rate: 4.5,
    price: 2999000,
    discount: 55,
    isBestSeller: true,
    stock: 15,
    flowerType: FlowerType.sunflower,
    style: Style.modern,
    size: Size.small,
    colors: [Color.yellow],
    categories: ["birthday-flowers", "seasonal-flowers"],
  },
  {
    slug: "mixed-pink-rose-lily-bouquet",
    images: [
      {
        url: "/images/MixedBouque.png",
        alt: "دسته گل ترکیبی رز صورتی و لیلیوم - نمای کامل",
      },
      {
        url: "/images/MixedBouque.png",
        alt: "دسته گل ترکیبی رز صورتی و لیلیوم - نمای کامل",
      },
    ],

    title: "دسته گل ترکیبی رز صورتی و لیلیوم",
    rate: 4.5,
    price: 4900000,
    discount: 55,
    isBestSeller: false,
    stock: 4,
    flowerType: FlowerType.mixed,
    style: Style.classic,
    size: Size.large,
    colors: [Color.pink, Color.white],
    categories: ["romantic-bouquet", "minimal-bouquets"],
  },
  {
    slug: "summer-sunflower-bouquet-2",
    images: [
      { url: "/images/sunflowers.png", alt: "دسته گل آفتابگردان تابستانی" },
      { url: "/images/sunflowers.png", alt: "دسته گل آفتابگردان تابستانی" },
    ],

    title: "دسته گل آفتابگردان تابستانی",
    rate: 4.5,
    price: 2999000,
    discount: 55,
    isBestSeller: true,
    stock: 15,
    flowerType: FlowerType.sunflower,
    style: Style.luxury,
    size: Size.large,
    colors: [Color.yellow],
    categories: ["romantic-bouquet", "minimal-bouquets"],
  },
];
